apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  # 'admin' em Base64
  username: YWRtaW4=
  # 'admin123' em Base64
  password: YWRtaW4xMjM=
  # 'sistema_db' em Base64 (possui o underline no nome sistema_db)
  dbname: c2lzdGVtYV9kYg==
