name: Pipeline Fullstack Funcionarios

on:
  push:
    branches: [ "main" ]

jobs:
  # --- BUILD DA API (Roda na Nuvem do GitHub) ---
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-funcionarios:latest

  # --- BUILD DO FRONTEND (Roda na Nuvem do GitHub) ---
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend-funcionarios:latest

  # --- DEPLOY NO SEU DEBIAN (Roda no seu Self-hosted Runner) ---
  deploy:
    runs-on: self-hosted  # <--- A MÁGICA ACONTECE AQUI
    needs: [build-backend, build-frontend] # Só começa após os builds terminarem
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Aplicar Manifestos no Kubernetes
        run: |
          # Aplica as mudanças nos arquivos YAML
          kubectl apply -f k8s/db-pvc.yaml
          kubectl apply -f k8s/db-statefulset.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/system-ingress.yaml

      - name: Forçar atualização dos Pods (Rollout)
        run: |
          # Como usamos a tag :latest, o K8s precisa de um "empurrão" para baixar a imagem nova
          kubectl rollout restart deployment api-funcionarios
          kubectl rollout restart deployment frontend-funcionarios
